apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    ami: ami-093467ec28ae4fe03
    instanceType: t2.micro
    region: us-west-2
    subnetIdRef:
      name: sample-subnet01
    tags:
      name: demo-instance

