apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: crossplane-system
stringData:
  creds: |
    [default]
    aws_access_key_id = AKIAXIBYK7W7YDL7PEMX
    aws_secret_access_key = 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
